apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dev-topic-1
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: staging-topic-1
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 2
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: prod-topic-1
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 4
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: pii-topic-1
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1